name: Build zig

on:
  - workflow_dispatch

jobs:
  build-wheels:
    name: build wheel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - x86_64-windows
          - aarch64-windows
          - x86-windows
          - x86_64-macos
          - aarch64-macos
          - x86_64-linux
          - aarch64-linux
          - x86-linux

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pipx run build -w
        working-directory: zig
        env:
          ZIG_PLATFORM: ${{ matrix.platform }}

      - name: Install test
        if: matrix.platform == 'x86_64-linux'
        run: |-
          pip install --no-index -f zig/dist/ zig-bin
          which zig
          zig version
          zig env

          cat <<EOF > main.zig
          const std = @import("std");

          pub fn main() !void {
              std.debug.print("Hello, World!\n", .{});
          }
          EOF

          zig run main.zig
          python -m zig run main.zig

      - uses: actions/upload-artifact@v4
        with:
          name: zig-${{ matrix.platform }}
          path: zig/dist

  build-sdist:
    name: build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: pipx run build -s
        working-directory: zig

      - uses: actions/upload-artifact@v4
        with:
          name: zig-sdist
          path: zig/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*

      - run: ls dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
