name: Build xh

on:
  - workflow_dispatch

jobs:
  wheel:
    name: build-${{ matrix.os }}-${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            flags: ""
            tag: manylinux_2_17_x86_64.manylinux2014_x86_64.musllinux_1_2_x86_64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            flags: ""
            tag: manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_2_aarch64
          - os: macos-13
            target: x86_64-apple-darwin
            flags: "--features=native-tls"
          - os: macos-latest
            target: aarch64-apple-darwin
            flags: "--features=native-tls"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            flags: "--features=native-tls"
            rustflags: -C target-feature=+crt-static
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            flags: "--features=native-tls"
            rustflags: -C target-feature=+crt-static

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init -- xh/xh
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: astral-sh/setup-uv@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set RUSTFLAGS env variable
        if: matrix.rustflags
        shell: bash
        run: echo "RUSTFLAGS=${{ matrix.rustflags }}" >> $GITHUB_ENV

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist ${{ matrix.flags }}
          target: ${{ matrix.target }}
          manylinux: musllinux_1_2
          working-directory: ./xh
          sccache: true

      - name: Post Processing wheel
        if: matrix.tag
        shell: bash
        run: |
          sudo chmod -R 777 dist
          uvx wheel tags --remove --platform-tag ${{ matrix.tag }} dist/*.whl
        working-directory: ./xh

      - run: ls -R xh/dist

      - name: Install test
        run: |-
          pip install --no-index -f xh/dist/ xh-bin
          which xh
          xh --version

          xh -I POST https://httpbingo.org/post foo=bar

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.target }}-${{ github.run_attempt }}
          path: xh/dist/*.whl
          if-no-files-found: error

  sdist:
    name: sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init -- xh/xh
      - uses: astral-sh/setup-uv@v6

      - run: uv build --sdist
        working-directory: ./xh

      - run: ls xh/dist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: xh/dist/*.tar.gz
          if-no-files-found: error

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [sdist, wheel]
    environment: publish
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - run: ls -R dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
