name: Build fzf

on:
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: git submodule update --init -- fzf/fzf
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - run: uv run build_wheel.py
        working-directory: ./fzf
      - run: uv build --sdist
        working-directory: ./fzf

      - run: |
          uv pip install --system --no-index -f fzf/dist/ fzf-bin
          fzf --version

          nohup fzf > log.log 2>&1 &
          sleep 2
          cat log.log

      - uses: actions/upload-artifact@v5
        with:
          path: fzf/dist

      - run: ls fzf/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v6
        with:
          name: artifact
          path: dist

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*
      - run: ls dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
