name: Build eget

on:
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init -- eget/eget
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - run: pip install build[virtualenv] wheel
      - run: python build_wheel.py
        working-directory: ./eget
      - run: python -m build -s
        working-directory: ./eget

      - run: |
          pip install --no-index -f eget/dist/ eget-py
          eget --version

      - uses: actions/upload-artifact@v4
        with:
          path: eget/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: dist/*
      - run: ls -R dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
