name: Build seaweedfs

on:
  - workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: git submodule update --init -- seaweedfs/seaweedfs
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - run: uv run build_wheel.py
        working-directory: ./seaweedfs
      - run: uv build --sdist
        working-directory: ./seaweedfs

      - run: |
          uv pip install --system --no-index -f seaweedfs/dist/ seaweedfs-bin
          weed version

          mkdir -p ./data123
          nohup weed server -master.port=49333 -volume.port=48080 -dir="./data123" -s3 > log.log 2>&1 &
          sleep 20
          cat log.log

      - uses: actions/upload-artifact@v4
        with:
          path: seaweedfs/dist

      - run: ls seaweedfs/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: artifact
          path: dist

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*

      - run: ls dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
