name: Build seaweedfs

on:
  - workflow_dispatch

jobs:
  wheel:
    name: build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - windows-latest
          - windows-11-arm

    steps:
      - uses: actions/checkout@v5
      - run: git submodule update --init -- seaweedfs/seaweedfs
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Build wheel
        run: uv build --wheel --config-setting=--seaweedfs-tags=5BytesOffset,sqlite
        working-directory: ./seaweedfs
      - name: Audit wheel
        if: runner.os == 'Linux'
        run: uvx auditwheel repair -w dist dist/*.whl
        working-directory: ./seaweedfs

      - run: |
          uv pip install --system --no-index -f seaweedfs/dist/ seaweedfs-bin
          weed version

          mkdir -p ./data123
          nohup weed server -master.port=49333 -volume.port=48080 -dir="./data123" -s3 > log.log 2>&1 &
          sleep 20
          cat log.log

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ github.run_attempt }}
          path: seaweedfs/dist

      - run: ls seaweedfs/dist

  sdist:
    name: build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: git submodule update --init -- seaweedfs/seaweedfs
      - uses: astral-sh/setup-uv@v7

      - name: Build sdist
        run: uv build --sdist
        working-directory: ./seaweedfs

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: seaweedfs/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [wheel, sdist]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*

      - run: ls dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
